export const PIN_LIST_REQUEST = "PIN_LIST_REQUEST";
export const PIN_LIST_SUCCESS = "PIN_LIST_SUCCESS";
export const PIN_LIST_FAIL = "PIN_LIST_FAIL";

export const PIN_CREATE_REQUEST = "PIN_CREATE_REQUEST";
export const PIN_CREATE_SUCCESS = "PIN_CREATE_SUCCESS";
export const PIN_CREATE_FAIL = "PIN_CREATE_FAIL";
